services:
    subrip_manager:
        class:  Robbixc\SubRipManagerBundle\Manager\SrtManager
    validator.unique.srtfile:
        class:  Robbixc\SubRipManagerBundle\Validator\Constraints\SrtFileValidator
        arguments: ["@subrip_manager"]
        tags:
            - { name: validator.constraint_validator, alias: srtfile_validator}      
        
